CREATE TABLE IF NOT EXISTS  USUARIO (
	ID		INTEGER auto_increment,
    NOME	VARCHAR(150),
    EMAIL	VARCHAR(100),
    LOGIN	VARCHAR(100),
    SENHA	VARCHAR(100),
    PRIMARY KEY (ID));
    
CREATE TABLE IF NOT EXISTS PRODUTO (
    ID				INTEGER auto_increment,
    CODIGO			VARCHAR(50),
    DESCRICAO		VARCHAR(150),
    UN_MEDIDA		VARCHAR(2),
    VALOR			FLOAT,
    ESTOQUE			FLOAT,
    FICHA_TECNICA 	VARCHAR(1000),
    PRIMARY KEY (ID));
   